### PR TITLE
Fix onClick for header sort

### PR DESCRIPTION
**Pull request by mglaman**
This was throwing errors. With this change it is now executing queries.

### CODE REVIEW

**Comment by mglaman** [comment]
This needs more work. The sort parameter is wrong, at least in my example.

**Comment by mglaman** [comment]
Needed something more like

```
  sortHandler = (sort, order) => {
    this.setState({
      filterParams: {
        ...this.state.filterParams,
        sort_by: sort,
        sort_order: order.toUpperCase()
      },
    }, () => this.fetchLogEntries(this.state.page));
  };
```

The combined filter is not correct.

**Comment by dawehner** [comment]
I added https://github.com/jsdrupal/drupal-react-db-log/pull/2 which seems to solve the issue for me.

**Comment by mattgrill** [comment]
@dawehner @mglaman Looks like both #1 and #2 fix the same issue?

**Comment by dawehner** [comment]
@mattgrill Well yeah, mine is fixing a bit more by also adding a tablesort

**Comment by mattgrill** [comment]
@dawehner Yeah, alright. I can close this one and we can merge the other.

**Pull request closed without merging**
